services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - mlruns:/opt/app/mlruns
    entrypoint: ["mlflow"]
    command:
      - server
      - --backend-store-uri
      - ${MLFLOW_BACKEND_URI:-/opt/app/mlruns}
      - --artifacts-destination
      - ${MLFLOW_ARTIFACTS_DEST:-/opt/app/mlruns}
      - --serve-artifacts
      - --host
      - 0.0.0.0
      - --port
      - "5000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:5000/').status==200 else 1)\""]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  prefect:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - prefect_home:/home/app/.prefect
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:4200/api/health').status==200 else 1)\""]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s

  pipeline:
    build:
      context: .
      target: runtime
    command: python -m src.run
    volumes:
      - .:/opt/app
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://mlflow:5000}
      - PREFECT_API_URL=http://prefect:4200/api
      - PYTHONUNBUFFERED=1
      - PREFECT_LOGGING_LEVEL=INFO
      - RICH_FORCE_TERMINAL=1
      - TERM=xterm-256color
      - FORCE_COLOR=1
    depends_on:
      mlflow:
        condition: service_healthy
      prefect:
        condition: service_healthy

  app:
    build:
      context: .
      target: runtime
    working_dir: /opt/app
    command: ["streamlit", "run", "app/app.py",
              "--server.address=0.0.0.0",
              "--server.port=8501",
              "--server.headless=true"]
    ports:
      - "8501:8501"
    volumes:
      - .:/opt/app
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://mlflow:5000}
    depends_on:
      mlflow:
        condition: service_healthy

volumes:
  prefect_home:
  mlruns:
